# generated by datamodel-codegen:
#   filename:  depositNFTs.json

from __future__ import annotations

from typing import List

from pydantic import BaseModel


class DepositNFTsParameter(BaseModel):
    __root__: List[str]
