# generated by datamodel-codegen:
#   filename:  nFT2Token.json

from __future__ import annotations

from typing import List

from pydantic import BaseModel
from pydantic import Extra


class NFT2TokenParameter(BaseModel):
    class Config:
        extra = Extra.allow

    _to: str
    min_tokens_out: str
    nft_ids: List[str]
