# generated by datamodel-codegen:
#   filename:  withdrawNFTs.json

from __future__ import annotations

from typing import List

from pydantic import BaseModel


class WithdrawNFTsParameter(BaseModel):
    __root__: List[str]
