# generated by datamodel-codegen:
#   filename:  withdrawAny.json

from __future__ import annotations

from typing import Optional

from pydantic import BaseModel
from pydantic import Extra


class Token(BaseModel):
    class Config:
        extra = Extra.forbid

    fa2_address: str
    token_id: Optional[str]


class WithdrawAnyParameter(BaseModel):
    class Config:
        extra = Extra.forbid

    amt: str
    token: Token
